### ISSUE TITLE
Guzzle error.

### ISSUE THREAD

**Issue by adrianlaraperez88** [googleapis/google-api-php-client#1537]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 6: SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054 (see http://curl.
haxx.se/libcurl/c/libcurl-errors.html)' in Path\CurlFactory.php:186
Stack trace:
#0 Path\includes\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 Paths\includes\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(Guzzl
eHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 Path\includes\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\
Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 Path\includes\vendor\guzzlehttp\guzzle\src\Ha inPath\includes\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 186

**Comment by adrianlaraperez88** [comment]
Is no bug is problem in the server and set_time_limit.thanks
