### ISSUE TITLE
Problem with p12 file

### ISSUE THREAD

**Issue by usefksa** [googleapis/google-api-php-client#160]
Hey,
I have problem with p12 file. I have a script that works fine on my laptop (PHP 5.4.24). The script can get the needed data from Google Analytics API without any problem. However, when I try to run the same script on my server, it is amazon ec2 (PHP 5.3.28), it did not work. I check the p12 path, it is correct with the correct permissions. 

Here is the SSL information from phpinfo();

```
OpenSSL support     enabled
OpenSSL Library Version     OpenSSL 1.0.1g-fips 7 Apr 2014
OpenSSL Header Version  OpenSSL 1.0.1e-fips 11 Feb 2013
```

Here is the error details:

```
PHP Fatal error:  Uncaught exception 'Google_Auth_Exception' with message 'Unable to parse the p12 file.  Is this a .p12 file?  Is the password correct?  OpenSSL error: ' in /var/www/html/vendor/google/apiclient/src/Google/Signer/P12.php:52\nStack trace:\n#0 /var/www/html/vendor/google/apiclient/src/Google/Auth/AssertionCredentials.php(127): Google_Signer_P12->__construct(false, 'notasecret')\n#1 /var/www/html/vendor/google/apiclient/src/Google/Auth/AssertionCredentials.php(109): Google_Auth_AssertionCredentials->makeSignedJwt(Array)\n#2 /var/www/html/vendor/google/apiclient/src/Google/Auth/OAuth2.php(287): Google_Auth_AssertionCredentials->generateAssertion()\n#3 /var/www/html/vendor/google/apiclient/src/Google/Auth/OAuth2.php(219): Google_Auth_OAuth2->refreshTokenWithAssertion()\n#4 /var/www/html/vendor/google/apiclient/src/Google/Service/Resource.php(176): Google_Auth_OAuth2->sign(Object(Google_Http_Request))\n#5 /var/www/html/vendor/google/apiclient/src/Google/Service/Analytics.php(1419): Google_Service_Resource->call('get', Arra in /var/www/html/vendor/google/apiclient/src/Google/Signer/P12.php on line 52
```

Please help me for fix this error. I tried the solution here but it did not work.
http://stackoverflow.com/questions/22079057/getting-unable-to-parse-the-p12-file-error-with-google-api-php-client

**Comment by ganey** [comment]
I spent ages trying to get this to work. In case anyone else ends up looking here, I ended up putting file_get_contents around the key location:

~~~~
 $credentials = new \Google_Auth_AssertionCredentials(
                    $client_email,
                    $scopes,
                    file_get_contents('/some/folder/keyname.p12)
                );
~~~~
