### ISSUE TITLE
Analytics API error

### ISSUE THREAD

**Issue by IceKreamy** [googleapis/google-api-php-client#1681]
Hi,

We have been using the Analtics API for the last few years without any problems.
In the last few weeks we have been getting consistent errors whenever we try to run our code.

Bellow is the error:

```
Fatal error: Uncaught Google_Service_Exception: Error calling GEThttps://www.googleapis.com/analytics/v3/data/ga?ids=ga%3A84766089&start-date=2005-01-01&end-date=today&metrics=ga%3Apageviews&dimensions=ga%3ApagePath&start-index=30001&max-results=5000: (500) There was an internal error. in /mnt/gfs/home/reports/vendor/google/apiclient/src/Google/Http/REST.php:79
Stack trace:
#0 /mnt/gfs/home/reports/vendor/google/apiclient/src/Google/Http/REST.php(44): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request))
#1 /mnt/gfs/home/reports/vendor/google/apiclient/src/Google/Client.php(556): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))
#2 /mnt/gfs/home/reports/vendor/google/apiclient/src/Google/Service/Resource.php(195): Google_Client->execute(Object(Google_Http_Request))
#3 /mnt/gfs/home/reports/vendor/google/apiclient/src/Google/Service/Analytics.php(1927): Google_Service_Resource->call('get', Array, 'Google_Service_...')
#4 /mnt/gf in /mnt/gfs/home/reports/vendor/google/apiclient/src/Google/Http/REST.php on line 79
```

Any help is appreciated. Thanks

**Comment by edc-appno** [comment]
Same here, I've updated to the latest v1 version of the code (v1.1.8) and the same Issue.
It seems to be a problem with the google API not responding correctly.
I'm planning to update to v2 of the client code to see if that has the same problem.

**Comment by jdpedrie** [comment]
Can you provide a code snippet demonstrating the issue?

**Comment by jdpedrie** [comment]
Please feel free to re-open with the requested information if you are still experiencing problems.
