### ISSUE TITLE
File not found, when using get on Drive

### ISSUE THREAD

**Issue by Dibbyo456** [googleapis/google-api-php-client#1782]
If I do

```php
$client = getClient();
$service = new Google_Service_Drive($client);

$optParams = [
  'fileId' => '{{redacted}}',
  'supportsAllDrives' => true,
  'supportsTeamDrives' => true,
];
$results = $service->files->get($optParams);

print_r($results);
```
it throws errors:

```php
Fatal error: Uncaught Google_Service_Exception: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "File not found: fileId,{{redacted}},supportsAllDrives,1,supportsTeamDrives,1.",
    "locationType": "parameter",
    "location": "fileId"
   }
  ],
  "code": 404,
  "message": "File not found: fileId,{{redacted}},supportsAllDrives,1,supportsTeamDrives,1."
 }
}
 in C:\www\testapp\inc\vendor\google\apiclient\src\Google\Http\REST.php:118
Stack trace:
#0 C:\www\testapp\inc\vendor\google\apiclient\src\Google\Http\REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#1 C:\www\testapp\inc\vendor\google\apiclient\src\Google\Task\Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#2 C:\www\testapp\inc\vendor\google\apiclient\src\Google\Http\REST.php(58): Google_Task_Runner->run()
#3 C: in C:\www\testapp\inc\vendor\google\apiclient\src\Google\Http\REST.php on line 118
```

But if I do,

```bash
curl \
  'https://www.googleapis.com/drive/v3/files/{{redacted}}?supportsAllDrives=true' \
  --header 'Authorization: Bearer {{redacted}}' \
  --header 'Accept: application/json' \
  --compressed
```

it works fine, with the response

```bash
{
 "kind": "drive#file",
 "id": "{{redacted}}",
 "name": "{{redacted}}.zip",
 "mimeType": "application/zip",
 "teamDriveId": "{{redacted}}",
 "driveId": "{{redacted}}"
}
```

**Comment by jdpedrie** [comment]
The signature for `Google_Service_Drive_Resource_Files::get()` is `($fileId, $optParams = [])`.

Try this instead:

```php
$optParams = [
  'supportsAllDrives' => true,
  'supportsTeamDrives' => true,
];
$results = $service->files->get($fileId, $optParams);
```

**Comment by Dibbyo456** [comment]
Oops.. Thank you.
