### ISSUE TITLE
Scope of `calendar.events` cause Fatal error

### ISSUE THREAD

**Issue by repsher** [googleapis/google-api-php-client#2020]
Found what I think is a bug. We had been using the full calendar scope for our project:
`$client->addScope("https://www.googleapis.com/auth/calendar");`
Which is working fine but we determined that we didn't need all the permissions that come with this scope so decided to downgrade to just the `calendar.events` scope:
`$client->addScope("https://www.googleapis.com/auth/calendar.events");`
I thought this would be an easy tweak and we get back a token but it looks like when `$client->setAccessToken(_TOKEN_HERE_);` is called it tosses a Fatal error which seems odd: 
`"message":"Request had insufficient authentication scopes.",`

#### Environment details

  - OS: Mac 10.15.7
  - PHP version: 7.3.11
  - Package name and version: google-api-php-client v2.8.3 (fresh install of composer & dependencies as of 12/21/20)

#### Steps to reproduce
I created a new example following the file upload example and can reproduce it there. You should be able to take the below, add it to the /examples dir and reproduce the issue. You can toggle the scopes from 'calendar.events' to 'calendar' to see that 'calendar' works fine while 'calendar.events' tosses an error. Maybe I'm missing something but seems like this should work fine.

#### Code example

```php
<?php
// spit out all errors
ini_set('display_startup_errors', 1);
ini_set('display_errors', 1);
error_reporting(-1);

include_once __DIR__ . '/../vendor/autoload.php';
include_once "templates/base.php";

echo pageHeader("Calendars");

/*************************************************
 * Ensure you've downloaded your oauth credentials
 ************************************************/
if (!$oauth_credentials = getOAuthCredentialsFile()) {
  echo missingOAuth2CredentialsWarning();
  return;
}

/************************************************
 * The redirect URI is to the current page, e.g:
 * http://localhost:8080/simple-file-upload.php
 ************************************************/
$redirect_uri = 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF'];

$client = new Google\Client();
$client->setAuthConfig($oauth_credentials);
$client->setRedirectUri($redirect_uri);
$client->setAccessType('offline');
$client->addScope("https://www.googleapis.com/auth/calendar.events"); // Fails
// $client->addScope("https://www.googleapis.com/auth/calendar"); // Works fine
$service = new Google_Service_Calendar($client);

// add "?logout" to the URL to remove a token from the session
if (isset($_REQUEST['logout'])) {
  unset($_SESSION['cal_token']);
}

/************************************************
 * If we have a code back from the OAuth 2.0 flow,
 * we need to exchange that with the
 * Google\Client::fetchAccessTokenWithAuthCode()
 * function. We store the resultant access token
 * bundle in the session, and redirect to ourself.
 ************************************************/
if (isset($_GET['code'])) {
  $token = $client->fetchAccessTokenWithAuthCode($_GET['code']);
  $client->setAccessToken($token);

  // store in the session also
  $_SESSION['cal_token'] = $token;

  // redirect back to the example
  header('Location: ' . filter_var($redirect_uri, FILTER_SANITIZE_URL));
}

// set the access token as part of the client
if (!empty($_SESSION['cal_token'])) {
  $client->setAccessToken($_SESSION['cal_token']);
  if ($client->isAccessTokenExpired()) {
    unset($_SESSION['cal_token']);
  }
} else {
  $authUrl = $client->createAuthUrl();
}

/************************************************
 * If we're signed in then list calendars
 ************************************************/
if ($_SERVER['REQUEST_METHOD'] == 'POST' && $client->getAccessToken()) {
  // get user's calendars
  $calendarList = $service->calendarList->listCalendarList();
  // loop
  $cals = array();
  while(true) {
    foreach ($calendarList->getItems() as $calendarListEntry) {
      $cals[] = array(
        'label' => $calendarListEntry->getSummary(),
        'id' => $calendarListEntry->getId(),
        'isPrimary' => $calendarListEntry->getPrimary()
      );
    }
    $pageToken = $calendarList->getNextPageToken();
    if ($pageToken) {
      $optParams = array('pageToken' => $pageToken);
      $calendarList = $gService->calendarList->listCalendarList($optParams);
    }
    else {
      break;
    }
  }
}
?>

<div class="box">
<?php if (isset($authUrl)): ?>
  <div class="request">
  <a class='login' href='<?= $authUrl ?>'>Connect Google Account</a>
  </div>
<?php elseif($_SERVER['REQUEST_METHOD'] == 'POST'): ?>
  <div class="shortened">
  <p>Your Calendars:</p>
  <ul>
  <?php foreach ($cals as $c) {echo '<li>'.$c['label'].'</li>';}?>
  </ul>
  </div>
<?php else: ?>
  <form method="POST">
  <input type="submit" value="Click here to list your calendars!" />
  </form>
<?php endif ?>
</div>

<?= pageFooter(__FILE__) ?>
```

**Resulting Error:**
```
"Fatal error":"Uncaught Google\\Service\\Exception":{
   "error":{
      "code":403,
      "message":"Request had insufficient authentication scopes.",
      "errors":[
         {
            "message":"Insufficient Permission",
            "domain":"global",
            "reason":"insufficientPermissions"
         }
      ],
      "status":"PERMISSION_DENIED"
   }
}
"in /google-api-php-client/src/Http/REST.php":128 Stack trace:#0 /google-api-php-client/src/Http/REST.php(103):"Google\\Http\\REST"::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response),Object(GuzzleHttp\Psr7\Request),"Google_Service_...") 
#1["internal function"]:"Google\\Http\\REST"::"doExecute(Object(GuzzleHttp\\Client)",Object(GuzzleHttp\Psr7\Request),"Google_Service_...") 
#2 /google-api-php-client/src/Task/Runner.php(181):"call_user_func_array(Array",Array) 
#3 /google-api-php-client/src/Http/REST.php(66):Google\Task\Runner->run() #4 /google-api-php-client in /google-api-php-client/src/Http/REST.php on line 128
```

**Comment by repsher** [comment]
Never mind, digging more it looks like the `calendar.events` scope just might not have permissions to list out the calendars.
Closing this out.
