### ISSUE TITLE
Fatal error: Uncaught Google_Service_Exception. Error 503

### ISSUE THREAD

**Issue by jaimevillanuadejuan** [googleapis/google-api-php-client#2053]
#### Environment details

  - OS: Windows 10
  - PHP version: 7.4.2
  - Composer version: 2.0.11

#### Steps to reproduce

  1. I've tried to run the command: "php quickstart.php" and I've got the following error.

```
require __DIR__ . '/vendor/autoload.php';

function getClient()
{
  $client = new Google_Client();
  $client->setApplicationName('Google Calendar API');
  $client->setScopes(Google_Service_Calendar::CALENDAR);
  $client->setAuthConfig(__DIR__ .'/credentials.json');
  $client->setAccessType('offline');
  $client->setApprovalPrompt('force');

    $tokenPath = 'token.json';
    if (file_exists($tokenPath)) {
        $accessToken = json_decode(file_get_contents($tokenPath), true);
        $client->setAccessToken($accessToken);
    }

    if ($client->isAccessTokenExpired()) {
      if ($client->getRefreshToken()) {
          $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());
      } else {
          $authUrl = $client->createAuthUrl();
          printf("Open the following link in your browser:\n%s\n", $authUrl);
          print 'Enter verification code: ';
          $authCode = trim(fgets(STDIN));

          $accessToken = $client->fetchAccessTokenWithAuthCode($authCode);
          $client->setAccessToken($accessToken);

          if (array_key_exists('error', $accessToken)) {
              throw new Exception(join(', ', $accessToken));
          }
          if (!file_exists(dirname($tokenPath))) {
            mkdir(dirname($tokenPath), 0700, true);
          }
          file_put_contents($tokenPath, json_encode($client->getAccessToken()));
      }
    }
    return $client;
}

$client = getClient();
$service = new Google_Service_Calendar($client);

$calendarId = 'primary';
$optParams = array(
  'maxResults' => 10,
  'orderBy' => 'startTime',
  'singleEvents' => true,
  'timeMin' => "0000-01-01T19:30:49+01:00",//date('c'),
);
$results = $service->events->listEvents($calendarId, $optParams);
$events = $results->getItems();

$d = new DateTime('2021-03-05');
$date = $d->format('Y-m-d\TH:i:sP');

$event = new Google_Service_Calendar_Event(array(
    'summary' => 'TEST 3 INSERT',
    'location' => 'location',
    'description' => 'TEST.',
    'start' => array(
      'dateTime' => date('c'),//(new DateTime)->setDate(2020,3,28)->format('Y-m-d\TH:i:sP'),
      'timeZone' => 'Europe/Madrid',
    ),
    'end' => array(
      'dateTime' => date('c'),//(new DateTime)->setDate(2020,5,03)->format('Y-m-d\TH:i:sP'),
      'timeZone' => 'Europe/Madrid',
    ),
    'attendees' => array(
      array('*' => '*'),
    ),
    'reminders' => array(
      'useDefault' => FALSE,
      'overrides' => array(
        array('method' => 'email', 'minutes' => 10),
        array('method' => 'popup', 'minutes' => 10),
      ),
    ),
  ));
  $calendarId = 'primary';
  $event = $service->events->insert($calendarId, $event);
  printf("Event created: </br> %s </br></br>\n", $event->htmlLink);if (empty($events)) {
    print "No upcoming events found.\n";
} else {
    print "All events: </br>\n";
    foreach ($events as $event) {
        $start = $event->start->dateTime;
        if (empty($start)) {
            $start = $event->start->date;
        }
        printf("%s %s (%s)\n", $event->getSummary(), $event->getDescription(), $start);
        print "</br>";
    }
}
echo date('c');
```

```php
# example
```

Here is the error:

Fatal error: Uncaught Google_Service_Exception: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "Backend Error"
   }
  ],
  "code": 503,
  "message": "Backend Error"
 }
}
 in C:\xampp\htdocs\TFG\vendor\google\apiclient\src\Google\Http\REST.php:118
Stack trace:
#0 C:\xampp\htdocs\TFG\vendor\google\apiclient\src\Google\Http\REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#1 C:\xampp\htdocs\TFG\vendor\google\apiclient\src\Google\Task\Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#2 C:\xampp\htdocs\TFG\vendor\google\apiclient\src\Google\Http\REST.php(58): Google_Task_Runner->run()
#3 C:\xampp\htdocs\TFG\vendor\google\apiclient\src\Google\Client.php(842): Google_Http_REST::execute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...', Array, NULL)
#4 C:\xampp\htdocs\TFG\vendor\ in C:\xampp\htdocs\TFG\vendor\google\apiclient\src\Google\Http\REST.php on line 118

**Comment by AlexxWide** [comment]
Have the same error. Noone can't really answer how to solve it. In 2022 i need to check it with my own hands and restart if needed. 4 days all is ok - but on 5 the same error. GA support can't answer and solve the problem. Sadly.

**Comment by bshaffer** [comment]
When I ran your code above, it executed fine. I had to make the following adjustments for it to work:

1. I had to enable the Calendar API in my project
2. After I did this, I received the following error:
```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "required",
    "message": "Missing attendee email."
   }
  ],
  "code": 400,
  "message": "Missing attendee email."
 }
}
```
3. So I changed the following line:
```
    'attendees' => array(
      array('*' => '*'),
    ),
```
to this:
```
    'attendees' => array(
      array('email' => $myEmail),
    ),
```

And I then received corresponding events from the calendar as expected!
