### ISSUE TITLE
OAuth Token URL is invalid

### ISSUE THREAD

**Issue by utdrmac** [googleapis/google-api-php-client#2328]
Trying to use the example code shown here: https://github.com/googleapis/google-api-php-client/blob/main/docs/oauth-web.md
My app successfully redirects to google login page, were I select my account, then accept the scope/permissions, and the callback URL is successfully accessed.

The issue is when I run `$client->authenticate($_GET['code']);` to get the token. This fails with the below stack trace.

```
if(isset($_GET["code"])) {

	// Google auth successful; received callback
	$client = new Google\Client();
	$client->setAuthConfig('../google_credentials.json');
	$client->addScope(Google\Service\Docs::DRIVE);
	$client->addScope(Google\Service\Docs::DOCUMENTS);

	$client->authenticate($_GET['code']); // This line fails, even when providing the received auth code.

	$_SESSION["GTOKEN"] = $client->getAccessToken();

	redirect("audits.php");
}

Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://oauth2.googleapis.com/token in /var/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210 
Stack trace:
 #0 /var/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
 #1 /var/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
 #2 /var/www/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
 #3 /var/www in /var/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210
```

**Comment by utdrmac** [comment]
I have similar code working just fine in my python stack. I even verified the token URL matches between PHP/Python google libraries. Just not working correctly on PHP side. If I try and access https://oauth2.googleapis.com/token in my browser, I get 404 Not Found.

**Comment by utdrmac** [comment]
I found the problem. SELinux was 'Enforcing' and blocking all outbound PHP/Curl connections.

**Comment by bshaffer** [comment]
Glad you got this figured out! Closing this as resolved.
